spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/prediman_crm
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://prediman.paulobof.com.br}
